spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springtest
    username: root
    password: 7jhjgcdu2rin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
